//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraCargas
    {
        public BitacoraCargas()
        {
            this.Comprobantes = new HashSet<Comprobantes>();
            this.Comprobantes1 = new HashSet<Comprobantes>();
            this.Evidencias = new HashSet<Evidencias>();
        }
    
        public int BitacoraCargaId { get; set; }
        public string NombreArchivo { get; set; }
        public string Extension { get; set; }
        public Nullable<bool> Activo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAltaId { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> UsuarioCambioId { get; set; }
    
        public virtual ICollection<Comprobantes> Comprobantes { get; set; }
        public virtual ICollection<Comprobantes> Comprobantes1 { get; set; }
        public virtual ICollection<Evidencias> Evidencias { get; set; }
    }
}
