//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobantes
    {
        public Comprobantes()
        {
            this.ComprobantesImpuestos = new HashSet<ComprobantesImpuestos>();
            this.Conceptos = new HashSet<Conceptos>();
            this.TimbresFiscalesDigitales = new HashSet<TimbresFiscalesDigitales>();
        }
    
        public int ComprobanteId { get; set; }
        public int EmisorId { get; set; }
        public int ReceptorId { get; set; }
        public Nullable<decimal> TotalImpuestosRetenidos { get; set; }
        public Nullable<decimal> TotalImpuestosTrasladados { get; set; }
        public string Certificado { get; set; }
        public string CondicionesPago { get; set; }
        public decimal Descuento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaFolioFiscalOrig { get; set; }
        public string Folio { get; set; }
        public string FolioFiscalOrig { get; set; }
        public string FormaPago { get; set; }
        public string LugarExpedicion { get; set; }
        public string MetodoPago { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> MontoFolioFiscalOrig { get; set; }
        public string MotivoDescuento { get; set; }
        public string NoCertificado { get; set; }
        public string NumCtaPago { get; set; }
        public string Sello { get; set; }
        public string Serie { get; set; }
        public string SerieFolioFiscalOrig { get; set; }
        public decimal SubTotal { get; set; }
        public string TipoCambio { get; set; }
        public string TipoComprobante { get; set; }
        public decimal Total { get; set; }
        public string Version { get; set; }
        public int BitacoraCargaIdXML { get; set; }
        public Nullable<int> BitacoraCargaIdPDF { get; set; }
        public Nullable<bool> Activo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAltaId { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> UsuarioCambioId { get; set; }
    
        public virtual BitacoraCargas BitacoraCargas { get; set; }
        public virtual BitacoraCargas BitacoraCargas1 { get; set; }
        public virtual ICollection<ComprobantesImpuestos> ComprobantesImpuestos { get; set; }
        public virtual ICollection<Conceptos> Conceptos { get; set; }
        public virtual ICollection<TimbresFiscalesDigitales> TimbresFiscalesDigitales { get; set; }
        public virtual Emisores Emisores { get; set; }
        public virtual Receptores Receptores { get; set; }
    }
}
