//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evidencias
    {
        public int EvidenciaId { get; set; }
        public int EmpresaId { get; set; }
        public Nullable<int> BancoId { get; set; }
        public int TipoTransaccionId { get; set; }
        public string NumeroTransferencia { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal MontoPago { get; set; }
        public string NoFacturaPagada { get; set; }
        public string ClaveEvidencia { get; set; }
        public int BitacoraCargaId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAltaId { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> UsuarioCambioId { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual BitacoraCargas BitacoraCargas { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual TiposTransacciones TiposTransacciones { get; set; }
    }
}
