//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacturacionEntities : DbContext
    {
        public FacturacionEntities()
            : base("name=FacturacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bancos> Bancos { get; set; }
        public virtual DbSet<BitacoraCargas> BitacoraCargas { get; set; }
        public virtual DbSet<Comprobantes> Comprobantes { get; set; }
        public virtual DbSet<ComprobantesImpuestos> ComprobantesImpuestos { get; set; }
        public virtual DbSet<Conceptos> Conceptos { get; set; }
        public virtual DbSet<Domicilios> Domicilios { get; set; }
        public virtual DbSet<Emisores> Emisores { get; set; }
        public virtual DbSet<EmisoresRegimenesFiscales> EmisoresRegimenesFiscales { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Evidencias> Evidencias { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Receptores> Receptores { get; set; }
        public virtual DbSet<RegimenesFiscales> RegimenesFiscales { get; set; }
        public virtual DbSet<TimbresFiscalesDigitales> TimbresFiscalesDigitales { get; set; }
        public virtual DbSet<TiposImpuesto> TiposImpuesto { get; set; }
        public virtual DbSet<TiposTransacciones> TiposTransacciones { get; set; }
    }
}
