//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public Personas()
        {
            this.Emisores = new HashSet<Emisores>();
            this.Receptores = new HashSet<Receptores>();
        }
    
        public int PersonaId { get; set; }
        public string Rfc { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAltaId { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> UsuarioCambioId { get; set; }
    
        public virtual ICollection<Emisores> Emisores { get; set; }
        public virtual ICollection<Receptores> Receptores { get; set; }
    }
}
