//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimbresFiscalesDigitales
    {
        public int TimbreFiscalDigitalId { get; set; }
        public int ComprobanteId { get; set; }
        public System.DateTime FechaTimbrado { get; set; }
        public string NoCertificadoSAT { get; set; }
        public string SelloCFD { get; set; }
        public string SelloSAT { get; set; }
        public string UUID { get; set; }
        public string Version { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAltaId { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> UsuarioCambioId { get; set; }
    
        public virtual Comprobantes Comprobantes { get; set; }
    }
}
