//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposImpuesto
    {
        public TiposImpuesto()
        {
            this.ComprobantesImpuestos = new HashSet<ComprobantesImpuestos>();
        }
    
        public int TipoImpuestoId { get; set; }
        public string TipoImpuesto { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAltaId { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> UsuarioCambioId { get; set; }
    
        public virtual ICollection<ComprobantesImpuestos> ComprobantesImpuestos { get; set; }
    }
}
